# NOTE: This image is ONLY for testing purposes.
ARG IMAGE_NAME=hardened-nginx
FROM $IMAGE_NAME:latest

EXPOSE 443

ENV HOST=localhost

# Do _NOT_ package a real certificate in a docker image
COPY cert /cert
# Copying the content and templates is OK, but mounting it as a volume is more flexible
COPY content /srv/content
COPY templates /etc/templates
